server:
  port: 8080
spring:
  messages:
    basename: messages
  security:
    user:
      name: user
      password: password
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false